language: python
python: '2.7'
env:
- PYTHONUNBUFFERED=1
before_install:
- sudo apt-get update -qq
install:
- pip install -U pip
- "printf '[defaults]\nroles_path=../' > ansible.cfg"
script:
- ansible-playbook -i hosts playbook.yml --syntax-check
- ansible-playbook -v -i test/hosts test/test.yml
