language: python
python: '2.7'
env:
- PYTHONUNBUFFERED=1
before_install:
- sudo apt-get update -qq
install:
- pip install -U pip
- pip install ansible
- "printf '[defaults]\nroles_path=../' > ansible.cfg"
script:
- ansible-playbook -i tests/hosts tests/test.yml --syntax-check
- ansible-playbook -v -i tests/hosts tests/test.yml
